djangoapp1/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^gaana/',include('gaana.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gaana/urls.py
from django.conf.urls import url
from .import views

app_name = 'gaana'
urlpatterns = [
    #/music/
    url(r'^$', views.IndexView.as_view(),name='index'),
    url(r'^login_user/$', views.login_user, name='login'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),

    #/music/7142/
    #url(r'^(?P<album_id>[0-9]+)/$',views.DetailView.as_view(),name='detail'),
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name='detail'),

    #/music/7142/favorite/
    #url(r'^(?P<album_id>[0-9]+)/favorite/$',views.isfavorite,name='favorite'),
    url(r'album/add/$',views.AlbumCreate.as_view(),name="album-add"),

    url(r'album/(?P<pk>[0-9]+)/$',views.AlbumUpdate.as_view(),name="album-update"),

    url(r'album/(?P<pk>[0-9]+)/delete/$',views.AlbumDelete.as_view(),name="album-delete"),

    url(r'album/(?P<album_id>[0-9]+)/delete/(?P<song_id>[0-9]+)/$',views.delete_song,name="delete_song"),

    url(r'^register/$',views.UserFormView.as_view(),name='register'),

    url(r'^(?P<album_id>[0-9]+)/create_song/$', views.CreateSong, name='create_song'),

    url(r'^(?P<song_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),

    #url(r'^(?P<filter_by>[a-zA_Z]+)/songs/$',views.songs(),name='songs'),
    #url(r'^(P<album_id>[0-9]+)/comment/$',views.add_comment,name='add_comment')


]

gaana/models.py
from django.db import models
from django.core.urlresolvers import reverse
from datetime import datetime,timezone
from django.contrib.auth.models import User,Permission

class Album(models.Model):
    user = models.ForeignKey(User, default=1)
    artist = models.CharField(max_length=100)
    album_title = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()
    is_favorite = models.BooleanField(default=False)


    def get_absolute_url(self):
        return reverse('gaana:detail',kwargs={'pk':self.pk})

    def __str__(self):
        return self.album_title+'-'+self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    song_title = models.CharField(max_length=500)
    song_file = models.FileField(default=None)
    #date = models.DateTimeField(default=datetime.now)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

class Comment(models.Model):
    album = models.ForeignKey(Album,on_delete=models.CASCADE)
    #obj_id = models.IntegerField()
    #userdetail = models.ForeignKey(User)
    content = models.TextField()
    #created_date = models.DateTimeField(default=datetime.now)
    #approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.content

    def get_absolute_url(self):
        return reverse('gaana:detail', kwargs={'pk': self.pk})


#class UserForm(models.User)
#can be inherited by using from django.contrib.auth.models import User

gaana/views.py
from django.views import generic
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import Album,Song,Comment
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import authenticate,login,logout
from django.views.generic import View
from .form import UserForm,SongForm,AlbumForm,CommentForm
from django.http import JsonResponse
from django.db.models import Q
from django.contrib.auth.decorators import login_required

@login_required
class IndexView(generic.ListView):
    template_name = 'gaana/index.html'
    context_object_name = 'albums'

    def get_queryset(self):
        return Album.objects.all()

@login_required    
class DetailView(generic.DetailView):
    model = Album
    template_name = 'gaana/detail.html'

    def post(self,request,pk):
        print(pk)
        #album = self.model
        album = Album.objects.get(pk=pk)
        form = CommentForm(request.POST or None)
        if form.is_valid():
            commentline = form.save(commit=False)
            commentline.album = album
            commentline.content = request.POST['content']
            commentline.save()
            comments = album.comment_set.all()
            context = {"comments": comments,
                       "comment_form": form}
            return redirect('gaana:detail', context)
        return render(request, self.template_name)


@login_required
class AlbumCreate(CreateView):
    model = Album
    fields = ['artist','album_title','genre','album_logo']

@login_required    
class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

@login_required    
class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('gaana:index')

# class SongCreate(CreateView):
#     model = Song
#     fields =['song_title','song_file']

@login_required
class UserFormView(View):
    form_class = UserForm
    template_name = 'gaana/registration_form.html'

    def get(self,request):
        form = self.form_class(None)
        return render(request,self.template_name,{'form':form})

    def post(self,request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            #cleaned data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            #returning user object if credentials are true
            user = authenticate(username=username,password=password)

            if user is not None:
                if user.is_active:
                    login(request,user)
                    return redirect('gaana:index')

        return render(request,self.template_name,{'form':form})

Audio_file_type=['mp3','wav','ogg']
Image_file_type = ['jpg','png','jpeg']

@login_required
def CreateSong(request,album_id):
    form = SongForm(request.POST or None, request.FILES or None)
    album = get_object_or_404(Album, pk=album_id)
    if form.is_valid():
        album_songs = album.song_set.all()
        for song in album_songs:
            if song.song_title == form.cleaned_data.get("song_title"):
                context = {'album':album,'form':form,'error_message':'Already in database'}
                return render(request,'gaana/create_song.html',context)
        song = form.save(commit=False)
        song.album = album
        song.song_file = request.FILES['song_file']
        file_type = song.song_file.url.split('.')[-1]
        file_type = file_type.lower()
        if file_type not in Audio_file_type:
            context = {'album':album,'form':form,'error_message':'File must be of type mp3,wav,ogg',}
            return render(request,'gaana/create_song.html',context)

        song.save()
        return render(request,'gaana/detail.html',{'album':album})
    context={'album':album,'form':form}
    return render(request,'gaana/create_song.html',context)

@login_required
class SongDelete(DeleteView):
    model = Song
    success_url = reverse_lazy('gaana/detail.html')

@login_required    
def delete_song(request, album_id, song_id):
    album = get_object_or_404(Album, pk=album_id)
    song = Song.objects.get(pk=song_id)
    song.delete()
    return render(request, 'gaana/detail.html', {'album': album})

@login_required
def favorite(request, song_id):
    song = get_object_or_404(Song, pk=song_id)
    try:
        if song.is_favorite:
            song.is_favorite = False
        else:
            song.is_favorite = True
        song.save()
    except (KeyError, Song.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})

@login_required    
def favorite_album(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        if album.is_favorite:
            album.is_favorite = False
        else:
            album.is_favorite = True
        album.save()
    except (KeyError, Album.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return JsonResponse({'success': True})

@login_required    
def songs(request,filter_by):
    if not request.user.is_autenticate():
        return render(request,'gaana/login.html')
    else:
        try:
            song_ids = []
            for album in Album.objects.filter(user=request.user):
                for song in album.song_set.all():
                    song_ids.append(song.pk)
            user_songs = Song.objects.filter(pk__in=song_ids)
            if filter_by == 'favorites':
                user_songs = user_songs.filter(is_favorite=True)
        except Album.DoesNotExist:
            user_songs = []
            return render(request,'gaana:songs',{'song_list':user_songs,'filter_by':filter_by})

# def add_comment(request,album_id):
#     album = get_object_or_404(Album, pk=album_id)
#     form = CommentForm(request.POST or None)
#     if form.is_valid():
#         comment = form.save(commit=False)
#         comment.album = album
#         comment.content = request.POST['content']
#         comment.save()
#         # content = form.cleaned_data.get('content')
#         # comment_obj = Comment(album=album,content=content)
#         # comment_obj.save()
#
#         comments = album.comment_set.all()
#         context = {"comments":comments,
#                "comment_form":form}
#         return redirect(request,'gaana:detail',context)
#     return render(request,'gaana/detail.html')



def login_user(request):
    if request.method=="POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username,password=password)
        if user is not None:
            if user.is_active:
                login(request,user)
                albums = Album.objects.get(user=request.user)
                return render(request,'gaana:index',{'albums':albums})
            else:
                return render(request,'gaana/login.html',{'error_message':'Session time out Please try again'})

        return render(request,'gaana/login.html',{'error_message':'Invalid credentials please try again'})

    return render(request,'gaana/login.html')

def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {'form':form,}
    return render(request,'gaana/login.html',context)

# from django.shortcuts import render,get_object_or_404
# from django.http import HttpResponse,Http404
#
# from .models import Album,Song
#
# def index(request):
#     all_albums = Album.objects.all()
#     context = {
#         'albums':all_albums,
#         'count':all_albums.count()
#     }
#     return render(request,'gaana/index.html',context)
# def detail(request,album_id):
#     album = get_object_or_404(Album,pk=album_id)
#     #or
#     # try:
#     #     album=Album.objects.get(pk=album_id)
#     # except Album.DoesNotExist:
#     #     raise Http404("Album does nt exist")
#     return render(request,'gaana/detail.html',{'album':album})
# def isfavorite(request,album_id):
#     album = get_object_or_404(Album, pk=album_id)
#     try:
#         selected_song = album.song_set.get(pk=request.POST['song'])
#     except (KeyError,Song.DoesNotExist):
#         return render(request,'gaana/detail.html',{'album':album,'error_message':"You did not select a valid song"})
#     else:
#         selected_song.is_favorite=True
#         selected_song.save()
#         return render(request, 'gaana/detail.html', {'album': album})

gaana/templates/gaana/album_form.html
{% extends 'gaana/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block albums_Active %}active{% endblock %}


{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" method="post" action="" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'gaana/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>

        </div>
    </div>


</div>
{% endblock %}

gaana/templates/gaana/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}GaanaSuno{% endblock %}</title>

<!--loads the path to your static file-->

{% load staticfiles %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link href="https://fonts.googleapis.com/css?family=Audiowide" rel="stylesheet">
<link rel="stylesheet" href="{% static 'gaana/style.css'%}" type="text/css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>



</head>
<body>
        <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = 'https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.10';
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

    <nav class="navbar navbar-success navbar-inverse">
    <div class="container-fluid">
       <!--Header-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'gaana:index' %}">GaanaSuno</a>
        </div>
        <!--Items-->
        <div class="collapse navbar-collapse" id="topNavBar">

            <ul class="nav navbar-nav">
                <li>
                    <a href="{% url 'gaana:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums

                    </a>

                </li>
                 <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; My Music

                    </a>

                </li>
            </ul>
            <form class="navbar-form navbar-left" roles="search" method="post" action="">
                <div class="form-group">
                    <input type="text" class="form-control col-lg-9" name="q" value="{{ songs }}" placeholder="Search.....">
                    <button type="submit" class="btn btn-secondry">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </div>



            </form>
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'gaana:album-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'gaana:logout_user' %}">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>

        </div>


    </div>
</nav>
   <div class="container-fluid">
       <div id="detail" class="form-group"></div>
    {% block body %}
    {% endblock %}
    </div>
   </div>

</body>
</html>

gaana/templates/gaana/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}GaanaSuno{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'gaana/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'gaana/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'gaana:index' %}">GaanaSuno</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'gaana:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'gaana:login' %}">Log In</a></li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

gaana/templates/gaana/detail.html
{% extends 'gaana/base.html' %}
{% block title %}{{ album }}{% endblock %}
{% block albums_active %}active{% endblock %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'gaana:detail' album.id %}">
                        {% if album.album_logo.url %}
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
{#                <li role="presentation" class="active"><a href="{% url 'gaana:detail' album.id %}">View All</a></li>#}
                <li role="presentation"><a href="{% url 'gaana:create_song' album.id %}">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Songs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Song File</th>
                            <th>Favorite</th>
                            <th>Actions</th>
                            <th>Share</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for song in album.song_set.all %}
                            <tr>
                                <td>{{ song.song_title }}</td>
                                <td>
                                    
                                    <a target="-_top" href="{{ song.song_file.url }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>

                                </td>
                                <td>
                                    <a href="{% url 'gaana:favorite' song.id %}"><span class="glyphicon glyphicon-heart {% if song.is_favorite %}active{% endif %}"></span></a>
                                </td>
                                <td>
                                    <form action="{% url 'gaana:delete_song' album.id song.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                                <td>
                                    <div class="fb-share-button" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button" data-size="small" data-mobile-iframe="true">
                                        <a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse">Share</a>
                                    </div>
{#                                    <a href="#" class="glyphicon glyphicon-share"></a>#}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                <div class="panel panel-body">
                    <p class="lead">Leave your Comments</p>
                     <hr>
                <div class="">
                    <div class="fb-comments w-8" data-href="{{ request.build_absolute_url }}" data-numposts="5"></div>
{#                    <form action="." method="POST">#}
{#                            {% csrf_token %}#}
{#                            <div class="form-group">#}
{#                                <input class="form-control" type="textarea" name="content">{{ comment_form }}</input>#}
{#                                <input type="submit" value="Post" class="btn btn-default">#}
{#                            </div>#}
{#                        </form>#}
{#                    <hr>#}
{#                        <p>{{ comments.count }} Comments</p>#}
{#                        {% for comment in comments %}#}
{#                                <ul class="list-group">#}
{#                                    <li class="list-group-item">#}
{#                                        <p>{{ comment.content }}</p>#}
{#                                        <footer>by {{ comment.userdetail }} | {{ comment.created_date }} ago</footer>#}
{#                                    </li>#}
{#                                </ul>#}
{#                        {% endfor %}#}
                </div>

                </div>
            </div>

        </div>
        <!--Bottom comment Info-->



                </div>


    </div>

</div>

{% endblock %}

gaana/templates/gaana/index.html
{% extends 'gaana/base.html' %}

{% block body %}
<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3>{{ user.username }}'s Albums</h3>
        </div>
{#    {% if albums %}#}
{#        {% if object %}#}
    {% if albums %}
        {# It can be anything by using context_object_name='your wished_name' in views #}

    <ul class="col-sm-4 col-md-12">
{#            {% for album in albums %}#}
{#            {% for album in object_list %}#}
        {% for album in albums %}
        <div class="col-sm-4 col-md-3">
            <div class="thumbnail">
                <!--Album logo-->
                <a href="{% url 'gaana:detail' album.id %}">
                    <div id="thumb">
                        <img src="{{ album.album_logo.url }}" class="img-responsive">
                    </div>
                </a>

                <div class="caption">
                    <h4>{{ album.album_title }}</h4>
                    <h6>{{ album.artist }}</h6>

                    <!--Details-->
                    <a href="{% url 'gaana:detail' album.id %}"></a>

                    <!--delete-->
                    <form action="{% url 'gaana:album-delete' album.id %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="album_id" value="{{ album.id }}"/>
                        <button type="submit" class="btn btn-default btn-sm">
                            <span class="glyphicon glyphicon-trash"></span>
                        </button>
                    </form>

                    <!--favorite-->
                    <a href="#" class="btn btn-default btn-sm btn-favorite">
                        <span class="glyphicon glyphicon-heart-empty {% if album.is_favorite %}active{% endif %}"></span>
                    </a>

                    <!--Update-->
                    <form action="{% url 'gaana:album-update' album.id %}" method="get" style="display: inline">
                        {% csrf_token %}
                        <input type="hidden" name="album_id" value="{{ album.id }}"/>
                        <button type="submit" class="btn btn-default btn-sm" value="Update">
                            <span class="glyphicon glyphicon-refresh"></span>
                        </button>
                    </form>
                </div>
            </div>
        </div>
        {% endfor %}
    </ul>
{% else %}
    <div class="col-sm-12">
    <br>
    <a href="{% url 'gaana:album-add' %}">
        <button class="btn btn-success">
            <span class="glyphicon glyphicon-plus"></span>&nbsp;Add an album
        </button>
    </a>
    </div>
{% endif %}
    </div>

 <!-- If user searches and there are songs -->
    {% if songs %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Songs</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Song Title</th>
                                    <th>Artist</th>
                                    <th>Audio File</th>
                                    <th>Album</th>
                                    <th>Favorite</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for song in songs %}
                                    <tr>
                                        <td>{{ song.song_title }}</td>
                                        <td>{{ song.album.artist }}</td>
                                        <td>
                                            <a target="_blank" href="{{ song.audio_file.url }}">
                                                <button type="button" class="btn btn-success btn-xs">
                                                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                                </button>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{% url 'gaana:detail' song.album.id %}">
                                                <img src="{{ song.album.album_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                            </a>
                                            <a href="{% url 'gaana:detail' song.album.id %}">{{ song.album.album_title }}</a>
                                        </td>
                                        <td>
                                            <a href="{% url 'gaana:favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}

gaana/templates/gaana/login.html
{% extends 'gaana/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'gaana:login'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Login</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'gaana:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}